# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            entity: { class: AppBundle\Models\User, property: username }

    encoders:
        AppBundle\Models\User:
            algorithm: bcrypt
            cost: 5

    firewalls:
        login_firewall:
            pattern:   ^/login_status$
            anonymous: ~
            context:   default_context
        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login_status
                username_parameter: username
                password_parameter: password
                always_use_default_target_path: true
                default_target_path: /login_status
            logout:
                path:   /logout
                target: /
            context: default_context

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_status, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
