# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    test_model_converter:
        class: AppBundle\Converter\TestModelConverter
        tags:
            - { name: request.param_converter, priority: -2, converter: test_model_converter }
    user_converter:
        class: AppBundle\Converter\UserConverter
        tags:
            - { name: request.param_converter, priority: -2, converter: user_converter }
        arguments: ["@doctrine.orm.entity_manager"]
    json_exception_listener:
        class: AppBundle\Listener\JsonExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 200 }
    user_manager:
        class: AppBundle\Manager\UserManager
        arguments: ["@doctrine.orm.default_entity_manager", "@validator", "@security.user_password_encoder.generic", "@security.token_storage"]
